# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 flxk1
"""Tests for the loomground-suite plugin's SessionStart runtime-check hook.

The loomground-suite plugin.json / .mcp.json launch `loomground-mcp`
unconditionally; if the loomground runtime is not installed that MCP server
start fails silently. `plugins/loomground-suite/hooks/session-start.sh` is a
Claude Code SessionStart hook that turns that into an actionable message,
without touching the pinned mcpServers configuration (see
test_package_build.py::test_suite_is_one_local_entry_point_with_valid_contract_schemas
and this module's own byte-identity checks for that pin).

The hook is POSIX sh (no python) because Claude Code on Windows runs plugin
hooks through Git Bash, and "Python is missing" is itself one of the cases
the hook must report -- so it cannot depend on Python to detect that.

The hook embeds a literal "3.12" Python range label rather than reading
runtime/runtime-sources.json at runtime (that file is JSON and the hook may
not shell out to python to parse it). That literal is GENERATED by
`tools/render_suite_hook.py` from
`loomground_installer.requirements.runtime_python_label` -- the single
short-label formatter also used by `loomground doctor` and the docs drift
test -- so there is exactly one place that formats the label. The label
names the whole supported range (not just its lower bound): for the real
repository's current single-minor range it happens to read like a bare
minimum ("3.12"), but for a same-major span it reads as "3.12-3.13", and
this module drives that exact case. This module is the guardrail, in two
layers:

* comparing the literal embedded in the committed hook against
  `runtime_python_label` resolved from the real `runtime-sources.json`,
  through this module's own `range_label_from_runtime_sources` -- which
  itself calls the one helper, so this is not a second formatter;
* driving the real generation path (`tools/render_suite_hook.py`, `--check`
  and render modes) against temp runtime-sources.json files -- including a
  same-major *span* range, where the short label is no longer just the
  minimum -- to prove the hook's label line is actually generated from the
  helper, not hand-copied.
"""
import json
import re
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HOOK = ROOT / "plugins/loomground-suite/hooks/session-start.sh"
HOOKS_JSON = ROOT / "plugins/loomground-suite/hooks/hooks.json"
RUNTIME_SOURCES = ROOT / "runtime/runtime-sources.json"

sys.path.insert(0, str(ROOT / "tools"))
import render_suite_hook  # noqa: E402


def range_label_from_runtime_sources(runtime_sources: Path = RUNTIME_SOURCES) -> str:
    """Resolve the short label from a runtime-sources.json via the one helper.

    ``runtime_sources`` may be the real repository file (the default) or a
    temp file a test writes -- either way this goes through
    ``tools/render_suite_hook.py``'s ``label_for_runtime_sources``, which
    itself resolves the range with ``supported_runtime_python`` and formats
    it with ``loomground_installer.requirements.runtime_python_label``, the
    single short-label formatter. No separate, from-scratch JSON parse lives
    here: this module has no second formatter to keep in sync.
    """
    return render_suite_hook.label_for_runtime_sources(runtime_sources)


def embedded_label_in_hook() -> str:
    text = HOOK.read_text(encoding="utf-8")
    match = re.search(r'PYTHON_RANGE_LABEL="([^"]+)"', text)
    assert match, "hook must set PYTHON_RANGE_LABEL=\"...\""
    return match.group(1)


def run_hook_at(path_value: str, hook: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [str(hook)],
        env={"PATH": path_value},
        text=True,
        capture_output=True,
        timeout=10,
    )


def run_hook(path_value: str) -> subprocess.CompletedProcess:
    return run_hook_at(path_value, HOOK)


class HookShapeTests(unittest.TestCase):
    def test_hooks_json_is_valid_json_in_the_plugin_hooks_schema(self):
        data = json.loads(HOOKS_JSON.read_text(encoding="utf-8"))
        # Plugin hooks.json wrapper format: {"hooks": {<EventName>: [...]}}.
        # Verified against the shipped, official plugin-dev "hook-development"
        # skill (Hook Configuration Formats / "Plugin hooks.json Format") and
        # against real installed plugins using this exact shape, e.g.
        # claude-plugins-official's learning-output-style and ctrl-engineering
        # plugin's hooks/hooks.json (both wrap SessionStart the same way).
        self.assertIn("hooks", data)
        self.assertIn("SessionStart", data["hooks"])
        entries = data["hooks"]["SessionStart"]
        self.assertIsInstance(entries, list)
        self.assertGreaterEqual(len(entries), 1)
        for entry in entries:
            for hook in entry["hooks"]:
                self.assertEqual(hook["type"], "command")
                self.assertIn("${CLAUDE_PLUGIN_ROOT}/hooks/session-start.sh", hook["command"])

    def test_hook_script_is_executable_and_posix_sh(self):
        self.assertTrue(HOOK.is_file())
        mode = HOOK.stat().st_mode
        self.assertTrue(mode & stat.S_IXUSR, "hook must be executable")
        first_line = HOOK.read_text(encoding="utf-8").splitlines()[0]
        self.assertEqual(first_line, "#!/bin/sh")

    def test_hook_script_never_invokes_python(self):
        # The word "python" legitimately appears in comments and in the
        # embedded message/label (the runtime it is checking for is a Python
        # runtime); what must never appear is an actual invocation of a
        # python interpreter as a command word. Strip comments and quoted
        # string contents, then check no remaining command word is python(3).
        code_lines = []
        for line in HOOK.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            # Drop double-quoted segments (the JSON payload and $MESSAGE
            # assignment live entirely inside these) so their contents can't
            # false-positive as command words.
            without_strings = re.sub(r'"[^"]*"', "", line)
            code_lines.append(without_strings)
        code_text = "\n".join(code_lines)
        for token in re.split(r"[\s;|&()<>]+", code_text):
            self.assertNotIn(token, ("python", "python3"), f"found a python invocation token: {token!r}")

    def test_mcp_servers_block_is_untouched_by_the_hook_addition(self):
        # The hook is an addition alongside .mcp.json / plugin.json, not a
        # replacement -- both must still carry the exact pinned MCP_SERVERS
        # block that tools/build_packages.py and other tests pin against.
        sys.path.insert(0, str(ROOT / "tools"))
        import build_packages  # noqa: E402

        suite = ROOT / "plugins/loomground-suite"
        mcp = json.loads((suite / ".mcp.json").read_text(encoding="utf-8"))
        claude = json.loads((suite / ".claude-plugin/plugin.json").read_text(encoding="utf-8"))
        self.assertEqual(mcp["mcpServers"], build_packages.MCP_SERVERS)
        self.assertEqual(claude["mcpServers"], build_packages.MCP_SERVERS)
        self.assertNotIn("hooks", claude, "hooks must ship via hooks/hooks.json auto-discovery, not plugin.json")


class HookBehaviorTests(unittest.TestCase):
    def test_silent_and_exit_zero_when_loomground_mcp_is_on_path(self):
        # A minimal stub executable named loomground-mcp is enough: the hook
        # only checks presence on PATH (`command -v`), it never runs it.
        import tempfile

        with tempfile.TemporaryDirectory() as stub_dir:
            stub_dir_path = Path(stub_dir)
            stub = stub_dir_path / "loomground-mcp"
            stub.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
            stub.chmod(0o755)
            result = run_hook(f"{stub_dir}:/usr/bin:/bin")

        self.assertEqual(result.returncode, 0)
        self.assertEqual(result.stdout, "")
        self.assertEqual(result.stderr, "")

    def test_actionable_message_and_exit_zero_when_loomground_mcp_is_missing(self):
        result = run_hook("/usr/bin:/bin")
        self.assertEqual(result.returncode, 0)

        label = range_label_from_runtime_sources()
        expected_message = (
            f"Loomground runtime not installed: run `loomground onboard` (Python {label} required)"
        )
        payload = json.loads(result.stdout)
        self.assertEqual(payload["systemMessage"], expected_message)
        self.assertEqual(payload["hookSpecificOutput"]["hookEventName"], "SessionStart")
        self.assertEqual(payload["hookSpecificOutput"]["additionalContext"], expected_message)


class RuntimeLabelDivergenceTests(unittest.TestCase):
    """Compare the hook's literal range label against the one helper's output.

    Non-vacuous: the first test is a real comparison between two
    independently-obtained values (the literal committed in the hook file,
    and `runtime_python_label()` resolved fresh from the real
    `runtime/runtime-sources.json`) that would fail the moment either one
    drifts from the other. The second test proves that sensitivity directly,
    by writing a temp copy of the hook with a deliberately wrong literal and
    showing the same comparison then disagrees.
    """

    def test_embedded_label_matches_runtime_sources_json(self):
        self.assertEqual(embedded_label_in_hook(), range_label_from_runtime_sources())

    def test_divergence_is_caught_if_hook_literal_diverges_from_helper(self):
        # A hook copy whose PYTHON_RANGE_LABEL literal has drifted from the
        # helper's output must be distinguishable by exactly the same
        # comparison the test above runs against the real, in-sync hook.
        real_label = range_label_from_runtime_sources()
        wrong_label = "9.99"
        self.assertNotEqual(real_label, wrong_label)

        with tempfile.TemporaryDirectory() as tmp:
            drifted = _copy_hook(Path(tmp))
            text = drifted.read_text(encoding="utf-8").replace(
                f'PYTHON_RANGE_LABEL="{real_label}"',
                f'PYTHON_RANGE_LABEL="{wrong_label}"',
            )
            self.assertNotEqual(text, drifted.read_text(encoding="utf-8"), "replacement did not apply")
            drifted.write_text(text, encoding="utf-8")

            match = re.search(r'PYTHON_RANGE_LABEL="([^"]+)"', drifted.read_text(encoding="utf-8"))
            self.assertEqual(match.group(1), wrong_label)
            self.assertNotEqual(match.group(1), range_label_from_runtime_sources())


class HookGenerationSyncTests(unittest.TestCase):
    """Prove the committed hook is generated by tools/render_suite_hook.py."""

    def test_committed_hook_is_in_sync_with_the_helper_for_the_real_file(self):
        result = render_suite_hook.main(
            ["--check", "--runtime-sources", str(RUNTIME_SOURCES), "--hook", str(HOOK)]
        )
        self.assertEqual(result, 0)

    def test_render_reproduces_the_committed_label_byte_for_byte(self):
        label = render_suite_hook.label_for_runtime_sources(RUNTIME_SOURCES)
        current_text = HOOK.read_text(encoding="utf-8")
        rendered = render_suite_hook.render(current_text, label)
        self.assertEqual(rendered, current_text)


def _write_runtime_sources(directory: Path, minimum, maximum_exclusive) -> Path:
    runtime_dir = directory / "runtime"
    runtime_dir.mkdir(parents=True, exist_ok=True)
    sources = runtime_dir / "runtime-sources.json"
    sources.write_text(
        json.dumps({"python": {"minimum": list(minimum), "maximum_exclusive": list(maximum_exclusive)}}),
        encoding="utf-8",
    )
    return sources


def _copy_hook(destination: Path) -> Path:
    copy = destination / "session-start.sh"
    copy.write_text(HOOK.read_text(encoding="utf-8"), encoding="utf-8")
    copy.chmod(0o755)
    return copy


class HookLabelRenderingFromTempFilesTests(unittest.TestCase):
    """Render a temp COPY of the hook from temp runtime-sources.json files.

    Covers both the single-minor case ((3,12)-(3,13), the real shape) and a
    same-major span ((3,12)-(3,14)), driving the real render tool and then
    actually executing the rendered sh script -- not just inspecting the
    generated text -- to assert on its real printed JSON message.
    """

    def _render_and_run(self, minimum, maximum_exclusive) -> subprocess.CompletedProcess:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            sources = _write_runtime_sources(tmp_path, minimum, maximum_exclusive)
            hook_copy = _copy_hook(tmp_path)

            exit_code = render_suite_hook.main(
                ["--runtime-sources", str(sources), "--hook", str(hook_copy)]
            )
            self.assertEqual(exit_code, 0)

            check_code = render_suite_hook.main(
                ["--check", "--runtime-sources", str(sources), "--hook", str(hook_copy)]
            )
            self.assertEqual(check_code, 0)

            return run_hook_at("/usr/bin:/bin", hook_copy)

    def test_single_minor_range_renders_3_12(self):
        result = self._render_and_run((3, 12), (3, 13))
        payload = json.loads(result.stdout)
        self.assertIn("(Python 3.12 required)", payload["systemMessage"])

    def test_same_major_span_renders_en_dash_range(self):
        result = self._render_and_run((3, 12), (3, 14))
        payload = json.loads(result.stdout)
        self.assertIn("(Python 3.12–3.13 required)", payload["systemMessage"])

    def test_rendered_temp_hook_is_still_silent_no_op_with_loomground_mcp_on_path(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            sources = _write_runtime_sources(tmp_path, (3, 12), (3, 14))
            hook_copy = _copy_hook(tmp_path)
            render_suite_hook.main(["--runtime-sources", str(sources), "--hook", str(hook_copy)])

            stub_dir = tmp_path / "stubbin"
            stub_dir.mkdir()
            stub = stub_dir / "loomground-mcp"
            stub.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
            stub.chmod(0o755)

            result = run_hook_at(f"{stub_dir}:/usr/bin:/bin", hook_copy)

        self.assertEqual(result.returncode, 0)
        self.assertEqual(result.stdout, "")
        self.assertEqual(result.stderr, "")


if __name__ == "__main__":
    unittest.main()
