# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 flxk1
"""Tests for the loomground-suite plugin's SessionStart runtime-check hook.

The loomground-suite plugin.json / .mcp.json launch `loomground-mcp`
unconditionally; if the loomground runtime is not installed that MCP server
start fails silently. `plugins/loomground-suite/hooks/session-start.sh` is a
Claude Code SessionStart hook that turns that into an actionable message,
without touching the pinned mcpServers configuration (see
test_package_build.py::test_suite_is_one_local_entry_point_with_valid_contract_schemas
and this module's own byte-identity checks for that pin).

The hook is POSIX sh (no python) because Claude Code on Windows runs plugin
hooks through Git Bash, and "Python is missing" is itself one of the cases
the hook must report -- so it cannot depend on Python to detect that.

The hook embeds a literal "3.12" Python label rather than reading
runtime/runtime-sources.json at runtime (that file is JSON and the hook may
not shell out to python to parse it). That literal is GENERATED by
`tools/render_suite_hook.py` from
`loomground_installer.requirements.runtime_python_label` -- the single
short-label formatter also used by `loomground doctor` and the docs drift
test -- so there is exactly one place that formats the label. This module
is the guardrail, in two layers:

* a from-scratch, independent re-derivation straight from JSON (not
  importing the helper), confirming the committed literal still matches
  `python.minimum` for the simple case where the real range is a single
  supported minor;
* driving the real generation path (`tools/render_suite_hook.py`, `--check`
  and render modes) against temp runtime-sources.json files -- including a
  same-major *span* range, where the short label is no longer just the
  minimum -- to prove the hook's label line is actually generated from the
  helper, not hand-copied.
"""
import json
import re
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HOOK = ROOT / "plugins/loomground-suite/hooks/session-start.sh"
HOOKS_JSON = ROOT / "plugins/loomground-suite/hooks/hooks.json"
RUNTIME_SOURCES = ROOT / "runtime/runtime-sources.json"

sys.path.insert(0, str(ROOT / "tools"))
import render_suite_hook  # noqa: E402


def minimum_python_label_from_runtime_sources() -> str:
    """Independent re-derivation of the supported minimum, straight from JSON.

    Deliberately does not import src/loomground_installer/requirements.py's
    helper, so this check does not merely restate that module's own logic --
    it is a second, from-scratch read of the single source-of-truth file.
    """
    data = json.loads(RUNTIME_SOURCES.read_text(encoding="utf-8"))
    major, minor = data["python"]["minimum"][:2]
    return f"{major}.{minor}"


def embedded_label_in_hook() -> str:
    text = HOOK.read_text(encoding="utf-8")
    match = re.search(r'PYTHON_MINIMUM_LABEL="([^"]+)"', text)
    assert match, "hook must set PYTHON_MINIMUM_LABEL=\"...\""
    return match.group(1)


def run_hook_at(path_value: str, hook: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        [str(hook)],
        env={"PATH": path_value},
        text=True,
        capture_output=True,
        timeout=10,
    )


def run_hook(path_value: str) -> subprocess.CompletedProcess:
    return run_hook_at(path_value, HOOK)


class HookShapeTests(unittest.TestCase):
    def test_hooks_json_is_valid_json_in_the_plugin_hooks_schema(self):
        data = json.loads(HOOKS_JSON.read_text(encoding="utf-8"))
        # Plugin hooks.json wrapper format: {"hooks": {<EventName>: [...]}}.
        # Verified against the shipped, official plugin-dev "hook-development"
        # skill (Hook Configuration Formats / "Plugin hooks.json Format") and
        # against real installed plugins using this exact shape, e.g.
        # claude-plugins-official's learning-output-style and ctrl-engineering
        # plugin's hooks/hooks.json (both wrap SessionStart the same way).
        self.assertIn("hooks", data)
        self.assertIn("SessionStart", data["hooks"])
        entries = data["hooks"]["SessionStart"]
        self.assertIsInstance(entries, list)
        self.assertGreaterEqual(len(entries), 1)
        for entry in entries:
            for hook in entry["hooks"]:
                self.assertEqual(hook["type"], "command")
                self.assertIn("${CLAUDE_PLUGIN_ROOT}/hooks/session-start.sh", hook["command"])

    def test_hook_script_is_executable_and_posix_sh(self):
        self.assertTrue(HOOK.is_file())
        mode = HOOK.stat().st_mode
        self.assertTrue(mode & stat.S_IXUSR, "hook must be executable")
        first_line = HOOK.read_text(encoding="utf-8").splitlines()[0]
        self.assertEqual(first_line, "#!/bin/sh")

    def test_hook_script_never_invokes_python(self):
        # The word "python" legitimately appears in comments and in the
        # embedded message/label (the runtime it is checking for is a Python
        # runtime); what must never appear is an actual invocation of a
        # python interpreter as a command word. Strip comments and quoted
        # string contents, then check no remaining command word is python(3).
        code_lines = []
        for line in HOOK.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                continue
            # Drop double-quoted segments (the JSON payload and $MESSAGE
            # assignment live entirely inside these) so their contents can't
            # false-positive as command words.
            without_strings = re.sub(r'"[^"]*"', "", line)
            code_lines.append(without_strings)
        code_text = "\n".join(code_lines)
        for token in re.split(r"[\s;|&()<>]+", code_text):
            self.assertNotIn(token, ("python", "python3"), f"found a python invocation token: {token!r}")

    def test_mcp_servers_block_is_untouched_by_the_hook_addition(self):
        # The hook is an addition alongside .mcp.json / plugin.json, not a
        # replacement -- both must still carry the exact pinned MCP_SERVERS
        # block that tools/build_packages.py and other tests pin against.
        sys.path.insert(0, str(ROOT / "tools"))
        import build_packages  # noqa: E402

        suite = ROOT / "plugins/loomground-suite"
        mcp = json.loads((suite / ".mcp.json").read_text(encoding="utf-8"))
        claude = json.loads((suite / ".claude-plugin/plugin.json").read_text(encoding="utf-8"))
        self.assertEqual(mcp["mcpServers"], build_packages.MCP_SERVERS)
        self.assertEqual(claude["mcpServers"], build_packages.MCP_SERVERS)
        self.assertNotIn("hooks", claude, "hooks must ship via hooks/hooks.json auto-discovery, not plugin.json")


class HookBehaviorTests(unittest.TestCase):
    def test_silent_and_exit_zero_when_loomground_mcp_is_on_path(self):
        # A minimal stub executable named loomground-mcp is enough: the hook
        # only checks presence on PATH (`command -v`), it never runs it.
        import tempfile

        with tempfile.TemporaryDirectory() as stub_dir:
            stub_dir_path = Path(stub_dir)
            stub = stub_dir_path / "loomground-mcp"
            stub.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
            stub.chmod(0o755)
            result = run_hook(f"{stub_dir}:/usr/bin:/bin")

        self.assertEqual(result.returncode, 0)
        self.assertEqual(result.stdout, "")
        self.assertEqual(result.stderr, "")

    def test_actionable_message_and_exit_zero_when_loomground_mcp_is_missing(self):
        result = run_hook("/usr/bin:/bin")
        self.assertEqual(result.returncode, 0)

        label = minimum_python_label_from_runtime_sources()
        expected_message = (
            f"Loomground runtime not installed: run `loomground onboard` (Python {label} required)"
        )
        payload = json.loads(result.stdout)
        self.assertEqual(payload["systemMessage"], expected_message)
        self.assertEqual(payload["hookSpecificOutput"]["hookEventName"], "SessionStart")
        self.assertEqual(payload["hookSpecificOutput"]["additionalContext"], expected_message)


class RuntimeLabelDivergenceTests(unittest.TestCase):
    def test_embedded_label_matches_runtime_sources_json(self):
        self.assertEqual(embedded_label_in_hook(), minimum_python_label_from_runtime_sources())

    def test_divergence_is_caught_if_runtime_sources_json_range_changes(self):
        # Simulate runtime-sources.json moving its minimum without the hook's
        # embedded literal following: the comparison above must fail in that
        # case. We prove it here without mutating the real file, by directly
        # asserting the two derivations disagree once we synthesize a moved
        # minimum -- i.e. the check is sensitive to the value, not vacuous.
        embedded = embedded_label_in_hook()
        moved = "9.99"
        self.assertNotEqual(embedded, moved)
        real = minimum_python_label_from_runtime_sources()
        self.assertNotEqual(real, moved)


class HookGenerationSyncTests(unittest.TestCase):
    """Prove the committed hook is generated by tools/render_suite_hook.py."""

    def test_committed_hook_is_in_sync_with_the_helper_for_the_real_file(self):
        result = render_suite_hook.main(
            ["--check", "--runtime-sources", str(RUNTIME_SOURCES), "--hook", str(HOOK)]
        )
        self.assertEqual(result, 0)

    def test_render_reproduces_the_committed_label_byte_for_byte(self):
        label = render_suite_hook.label_for_runtime_sources(RUNTIME_SOURCES)
        current_text = HOOK.read_text(encoding="utf-8")
        rendered = render_suite_hook.render(current_text, label)
        self.assertEqual(rendered, current_text)


def _write_runtime_sources(directory: Path, minimum, maximum_exclusive) -> Path:
    runtime_dir = directory / "runtime"
    runtime_dir.mkdir(parents=True, exist_ok=True)
    sources = runtime_dir / "runtime-sources.json"
    sources.write_text(
        json.dumps({"python": {"minimum": list(minimum), "maximum_exclusive": list(maximum_exclusive)}}),
        encoding="utf-8",
    )
    return sources


def _copy_hook(destination: Path) -> Path:
    copy = destination / "session-start.sh"
    copy.write_text(HOOK.read_text(encoding="utf-8"), encoding="utf-8")
    copy.chmod(0o755)
    return copy


class HookLabelRenderingFromTempFilesTests(unittest.TestCase):
    """Render a temp COPY of the hook from temp runtime-sources.json files.

    Covers both the single-minor case ((3,12)-(3,13), the real shape) and a
    same-major span ((3,12)-(3,14)), driving the real render tool and then
    actually executing the rendered sh script -- not just inspecting the
    generated text -- to assert on its real printed JSON message.
    """

    def _render_and_run(self, minimum, maximum_exclusive) -> subprocess.CompletedProcess:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            sources = _write_runtime_sources(tmp_path, minimum, maximum_exclusive)
            hook_copy = _copy_hook(tmp_path)

            exit_code = render_suite_hook.main(
                ["--runtime-sources", str(sources), "--hook", str(hook_copy)]
            )
            self.assertEqual(exit_code, 0)

            check_code = render_suite_hook.main(
                ["--check", "--runtime-sources", str(sources), "--hook", str(hook_copy)]
            )
            self.assertEqual(check_code, 0)

            return run_hook_at("/usr/bin:/bin", hook_copy)

    def test_single_minor_range_renders_3_12(self):
        result = self._render_and_run((3, 12), (3, 13))
        payload = json.loads(result.stdout)
        self.assertIn("(Python 3.12 required)", payload["systemMessage"])

    def test_same_major_span_renders_en_dash_range(self):
        result = self._render_and_run((3, 12), (3, 14))
        payload = json.loads(result.stdout)
        self.assertIn("(Python 3.12–3.13 required)", payload["systemMessage"])

    def test_rendered_temp_hook_is_still_silent_no_op_with_loomground_mcp_on_path(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            sources = _write_runtime_sources(tmp_path, (3, 12), (3, 14))
            hook_copy = _copy_hook(tmp_path)
            render_suite_hook.main(["--runtime-sources", str(sources), "--hook", str(hook_copy)])

            stub_dir = tmp_path / "stubbin"
            stub_dir.mkdir()
            stub = stub_dir / "loomground-mcp"
            stub.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
            stub.chmod(0o755)

            result = run_hook_at(f"{stub_dir}:/usr/bin:/bin", hook_copy)

        self.assertEqual(result.returncode, 0)
        self.assertEqual(result.stdout, "")
        self.assertEqual(result.stderr, "")


if __name__ == "__main__":
    unittest.main()
