#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 flxk1
"""Resolve exact PyPI release-file hashes for the runtime's pinned dependencies."""

from __future__ import annotations

import argparse
import json
import re
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path

from packaging.requirements import InvalidRequirement, Requirement

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "runtime" / "third-party-requirements.in"
DEFAULT_OUTPUT = ROOT / "runtime" / "third-party-requirements.txt"
SHA256 = re.compile(r"^[0-9a-f]{64}$")
HASH_LINE = re.compile(r"^\s+--hash=sha256:([0-9a-f]{64})(?: \\)?$")


def load_pins(path: Path) -> list[Requirement]:
    pins = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        requirement = Requirement(line)
        if requirement.url or requirement.marker or requirement.extras:
            raise ValueError(f"third-party pin must be a plain package==version: {line}")
        specifiers = list(requirement.specifier)
        if len(specifiers) != 1 or specifiers[0].operator != "==" or "*" in specifiers[0].version:
            raise ValueError(f"third-party pin must contain one exact version: {line}")
        pins.append(requirement)
    if not pins:
        raise ValueError("third-party input contains no pins")
    names = [pin.name.lower().replace("_", "-") for pin in pins]
    if names != sorted(names) or len(names) != len(set(names)):
        raise ValueError("third-party pins must have unique names in canonical sort order")
    return pins


def release_hashes(requirement: Requirement) -> tuple[str, ...]:
    version = next(iter(requirement.specifier)).version
    name = urllib.parse.quote(requirement.name, safe="")
    url = f"https://pypi.org/pypi/{name}/{urllib.parse.quote(version, safe='')}/json"
    with urllib.request.urlopen(url, timeout=30) as response:  # noqa: S310 - fixed HTTPS origin
        document = json.load(response)
    if document.get("info", {}).get("version") != version:
        raise ValueError(f"PyPI returned the wrong version for {requirement.name}=={version}")
    hashes = sorted({
        item.get("digests", {}).get("sha256", "")
        for item in document.get("urls", [])
        if item.get("packagetype") == "bdist_wheel" and not item.get("yanked", False)
    })
    if not hashes or any(not SHA256.fullmatch(value) for value in hashes):
        raise ValueError(f"no valid non-yanked wheel hashes for {requirement.name}=={version}")
    return tuple(hashes)


def render_lock(pins: list[Requirement]) -> str:
    lines = [
        "# Generated by tools/lock_runtime_third_party.py; do not edit.",
        "# Every accepted archive is an exact non-yanked wheel from pypi.org.",
    ]
    for requirement in pins:
        hashes = release_hashes(requirement)
        lines.append(f"{requirement} \\")
        for index, digest in enumerate(hashes):
            suffix = " \\" if index < len(hashes) - 1 else ""
            lines.append(f"    --hash=sha256:{digest}{suffix}")
    return "\n".join(lines) + "\n"


def validate_hash_lock(input_path: Path, lock_path: Path) -> None:
    expected = [str(requirement) for requirement in load_pins(input_path)]
    actual = []
    hashes: list[str] = []
    current = None
    for raw in lock_path.read_text(encoding="utf-8").splitlines():
        if not raw or raw.startswith("#"):
            continue
        if raw[:1].isspace():
            match = HASH_LINE.fullmatch(raw)
            if current is None or match is None:
                raise ValueError(f"invalid hash-lock continuation: {raw}")
            hashes.append(match.group(1))
            continue
        if current is not None and not hashes:
            raise ValueError(f"hash lock entry has no wheel hashes: {current}")
        current = raw.removesuffix(" \\")
        try:
            requirement = Requirement(current)
        except InvalidRequirement as exc:
            raise ValueError(f"invalid hash-lock requirement: {current}") from exc
        actual.append(str(requirement))
        hashes = []
    if current is not None and not hashes:
        raise ValueError(f"hash lock entry has no wheel hashes: {current}")
    if actual != expected:
        raise ValueError(f"hash lock entries differ from input: expected={expected}, actual={actual}")


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as stream:
        temporary = Path(stream.name)
        stream.write(content)
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render_lock(load_pins(args.input))
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != content:
            raise SystemExit(f"stale runtime dependency lock: {args.output}")
    else:
        write_atomic(args.output, content)
        print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
